const { Schema, model } = require("mongoose");

const albumSchema = new Schema({
  title: { type: String, required: true },
  artist: { type: String, required: true },
  release_date: { String },
  genres: {
    type: String,
    required: true,
    enum: [
      "2-Step",
      "AOR",
      "Abstract Hip Hop",
      "Acid House",
      "Acid Jazz",
      "Acid Rock",
      "Acid Techno",
      "Acoustic Rock",
      "Adult Contemporary",
      "Afro-Cuban Jazz",
      "Afro-Jazz",
      "Afrobeat",
      "Afrobeats",
      "Alt-Country",
      "Alt-Pop",
      "Alternative Dance",
      "Alternative Metal",
      "Alternative R&B",
      "Alternative Rock",
      "Ambient",
      "Ambient Dub",
      "Ambient House",
      "Ambient Pop",
      "Ambient Techno",
      "American Folk Music",
      "American Primitivism",
      "Americana",
      "Anarcho-Punk",
      "Anti-Folk",
      "Art Pop",
      "Art Punk",
      "Art Rock",
      "Atmospheric Black Metal",
      "Atmospheric Drum and Bass",
      "Atmospheric Sludge Metal",
      "Avant-Folk",
      "Avant-Garde Jazz",
      "Avant-Garde Metal",
      "Avant-Prog",
      "Baggy",
      "Balearic Beat",
      "Ballet",
      "Ballroom",
      "Baltimore Club",
      "Baroque Pop",
      "Beat Music",
      "Beatdown Hardcore",
      "Bebop",
      "Bedroom Pop",
      "Berlin School",
      "Big Band",
      "Big Beat",
      "Big Music",
      "Bitpop",
      "Black 'n' Roll",
      "Black Metal",
      "Blackened Death Metal",
      "Blackgaze",
      "Blue-Eyed Soul",
      "Blues",
      "Blues Rock",
      "Bolero",
      "Boogie",
      "Boogie Rock",
      "Boom Bap",
      "Bossa Nova",
      "Breakbeat",
      "Breakbeat Hardcore",
      "Breakcore",
      "Brega",
      "Brega calypso",
      "Brill Building",
      "British Folk Rock",
      "Britpop",
      "Broken Transmission",
      "Brutal Death Metal",
      "Brutal Prog",
      "Bubblegum Bass",
      "Canterbury Scene",
      "Celtic Folk",
      "Celtic Rock",
      "Chamber Folk",
      "Chamber Jazz",
      "Chamber Music",
      "Chamber Pop",
      "Chanson",
      "Chicago Drill",
      "Chicago Soul",
      "Children's Music",
      "Chillout",
      "Chillwave",
      "Chipmunk Soul",
      "Chiptune",
      "Chopped and Screwed",
      "Choral",
      "Christian Rock",
      "Christmas",
      "Cinematic Classical",
      "City Pop",
      "Cloud Rap",
      "Coldwave",
      "Comedy",
      "Comedy Rock",
      "Conscious Hip Hop",
      "Contemporary Country",
      "Contemporary Folk",
      "Contemporary R&B",
      "Cool Jazz",
      "Country",
      "Country Pop",
      "Country Rock",
      "Country Soul",
      "Cowpunk",
      "Crunk",
      "Crust Punk",
      "Cumbia",
      "Cyber Metal",
      "D-Beat",
      "Dance-Pop",
      "Dance-Punk",
      "Dariacore",
      "Dark Ambient",
      "Dark Cabaret",
      "Dark Folk",
      "Dark Jazz",
      "Darkwave",
      "Death Doom Metal",
      "Death Industrial",
      "Death Metal",
      "Death-Thrash",
      "Deathcore",
      "Deathgrind",
      "Deathrock",
      "Deconstructed Club",
      "Deep House",
      "Deep Soul",
      "Deep Tech",
      "Depressive Black Metal",
      "Digicore",
      "Digital Fusion",
      "Digital Hardcore",
      "Dirty South",
      "Disco",
      "Dissonant Death Metal",
      "Diva House",
      "Dixieland",
      "Djent",
      "Doom Metal",
      "Doomgaze",
      "Downtempo",
      "Dream Pop",
      "Dreampunk",
      "Drill",
      "Drill and Bass",
      "Drone",
      "Drone Metal",
      "Drum and Bass",
      "Drumless",
      "Dub",
      "Dub Techno",
      "Dubstep",
      "EBM",
      "ECM Style Jazz",
      "East Coast Hip Hop",
      "Easy Listening",
      "Easycore",
      "Electro",
      "Electro House",
      "Electro-Disco",
      "Electro-Industrial",
      "Electroacoustic",
      "Electroclash",
      "Electronic",
      "Electronic Dance Music",
      "Electropop",
      "Emo",
      "Emo Rap",
      "Emo-Pop",
      "Emocore",
      "Emoviolence",
      "Epic Collage",
      "Epic Doom Metal",
      "Ethereal Wave",
      "Euro-Disco",
      "Eurodance",
      "European Free Jazz",
      "Europop",
      "Experimental",
      "Experimental Hip Hop",
      "Experimental Rock",
      "Flamenco Pop",
      "Flamenco nuevo",
      "Folk",
      "Folk Metal",
      "Folk Pop",
      "Folk Punk",
      "Folk Rock",
      "Folktronica",
      "Footwork",
      "Forró eletrônico",
      "Freak Folk",
      "Freakbeat",
      "Free Folk",
      "Free Improvisation",
      "Free Jazz",
      "French Electro",
      "French House",
      "French Pop",
      "Funeral Doom Metal",
      "Funk",
      "Funk 150 bpm",
      "Funk Metal",
      "Funk Rock",
      "Funk brasileiro",
      "Funk carioca",
      "Funk mandelão",
      "Funky House",
      "Future Bass",
      "Future Funk",
      "Future Garage",
      "Futurepop",
      "G-Funk",
      "Gabber",
      "Gangsta Rap",
      "Garage Punk",
      "Garage Rock",
      "Garage Rock Revival",
      "Geek Rock",
      "Ghazal",
      "Girl Group",
      "Glam Metal",
      "Glam Punk",
      "Glam Rock",
      "Glitch",
      "Glitch Hop",
      "Glitch Pop",
      "Gospel",
      "Gothic Country",
      "Gothic Metal",
      "Gothic Rock",
      "Greek Folk Music",
      "Grime",
      "Grindcore",
      "Groove Metal",
      "Grunge",
      "Hard Bop",
      "Hard Dance",
      "Hard Rock",
      "Hardcore Breaks",
      "Hardcore Hip Hop",
      "Hardcore Punk",
      "Hardcore [EDM]",
      "Harsh Noise",
      "Hauntology",
      "Heartland Rock",
      "Heavy Metal",
      "Heavy Psych",
      "HexD",
      "Hi-NRG",
      "Hip Hop",
      "Hip Hop Soul",
      "Hip House",
      "Horror Punk",
      "Horrorcore",
      "House",
      "Hymns",
      "Hyperpop",
      "Hypnagogic Pop",
      "IDM",
      "Illbient",
      "Indie Folk",
      "Indie Pop",
      "Indie Rock",
      "Indie Surf",
      "Indietronica",
      "Industrial",
      "Industrial Hip Hop",
      "Industrial Metal",
      "Industrial Rock",
      "Instrumental Hip Hop",
      "Irish Folk Music",
      "J-Pop",
      "J-Rock",
      "J-core",
      "Jam Band",
      "Jangle Pop",
      "Jazz",
      "Jazz Fusion",
      "Jazz Pop",
      "Jazz Rap",
      "Jazz manouche",
      "Jazz-Funk",
      "Jazz-Rock",
      "Jazzstep",
      "Jungle",
      "K-Pop",
      "Krautrock",
      "Latin Alternative",
      "Latin Electronic",
      "Latin Jazz",
      "Latin Pop",
      "Latin Rap",
      "Latin Rock",
      "Liquid Drum and Bass",
      "Lo-Fi Hip Hop",
      "Lounge",
      "MPB",
      "Mandopop",
      "Maracatu",
      "Mashcore",
      "Mashup",
      "Math Pop",
      "Math Rock",
      "Mathcore",
      "Melodic Black Metal",
      "Melodic Death Metal",
      "Melodic Hardcore",
      "Melodic Metalcore",
      "Memphis Rap",
      "Merseybeat",
      "Metalcore",
      "Miami Bass",
      "Microhouse",
      "Midwest Emo",
      "Minimal Synth",
      "Minimal Techno",
      "Minimal Wave",
      "Minimalism",
      "Modal Jazz",
      "Modern Classical",
      "Moogsploitation",
      "Motown Sound",
      "Musical Parody",
      "Musique concrète",
      "NWOBHM",
      "Nashville Sound",
      "Neo-Psychedelia",
      "Neo-Soul",
      "Neoclassical Darkwave",
      "Neoclassical Metal",
      "Neoclassical New Age",
      "Neofolk",
      "Neoperreo",
      "Nerdcore Techno",
      "Neue Deutsche Härte",
      "New Age",
      "New Beat",
      "New Jack Swing",
      "New Rave",
      "New Wave",
      "No Wave",
      "Noise",
      "Noise Pop",
      "Noise Rock",
      "Noisecore",
      "Nu Jazz",
      "Nu Metal",
      "Nu-Disco",
      "Nu-Metalcore",
      "Orchestral",
      "Outlaw Country",
      "Outsider House",
      "Pagan Metal",
      "Piano Blues",
      "Piano Rock",
      "Pigfuck",
      "Plugg",
      "PluggnB",
      "Plunderphonics",
      "Poetry",
      "Political Hip Hop",
      "Pop",
      "Pop Punk",
      "Pop Rap",
      "Pop Reggae",
      "Pop Rock",
      "Pop Soul",
      "Post-Black Metal",
      "Post-Bop",
      "Post-Britpop",
      "Post-Grunge",
      "Post-Hardcore",
      "Post-Industrial",
      "Post-Metal",
      "Post-Minimalism",
      "Post-Punk",
      "Post-Punk Revival",
      "Post-Rock",
      "Power Metal",
      "Power Pop",
      "Powerviolence",
      "Progressive Big Band",
      "Progressive Breaks",
      "Progressive Country",
      "Progressive Death Metal",
      "Progressive Electronic",
      "Progressive Folk",
      "Progressive House",
      "Progressive Metal",
      "Progressive Metalcore",
      "Progressive Pop",
      "Progressive Rock",
      "Progressive Soul",
      "Proto-punk",
      "Psychedelic Folk",
      "Psychedelic Pop",
      "Psychedelic Rock",
      "Psychedelic Soul",
      "Psychobilly",
      "Pub Rock",
      "Punk",
      "Punk Blues",
      "Punk Rock",
      "Queercore",
      "R&B",
      "Rage",
      "Ragtime",
      "Rap Metal",
      "Rap Rock",
      "Raw Black Metal",
      "Red Dirt",
      "Reggae",
      "Reggaeton",
      "Rhythm and Blues",
      "Riddim",
      "Riot Grrrl",
      "Ritual Ambient",
      "Rock",
      "Rock & Roll",
      "Rock Opera",
      "Rockabilly",
      "Roots Reggae",
      "Roots Rock",
      "Salsa",
      "Samba",
      "Samba-Jazz",
      "Samba-rock",
      "Sampledelia",
      "Sasscore",
      "Screamo",
      "Sequencer & Tracker",
      "Shibuya-kei",
      "Shoegaze",
      "Show Tunes",
      "Singer-Songwriter",
      "Ska",
      "Ska Punk",
      "Skate Punk",
      "Slacker Rock",
      "Slowcore",
      "Sludge Metal",
      "Slushwave",
      "Smooth Soul",
      "Soft Rock",
      "Sophisti-Pop",
      "Soul",
      "Sound Collage",
      "Southern Gospel",
      "Southern Hip Hop",
      "Southern Rock",
      "Southern Soul",
      "Space Age Pop",
      "Space Ambient",
      "Space Disco",
      "Space Rock",
      "Space Rock Revival",
      "Speed Garage",
      "Speed Metal",
      "Speedcore",
      "Spiritual Jazz",
      "Spoken Word",
      "Stand-Up Comedy",
      "Standards",
      "Stoner Metal",
      "Stoner Rock",
      "Sunshine Pop",
      "Surf Punk",
      "Swancore",
      "Swing",
      "Symphonic Black Metal",
      "Symphonic Metal",
      "Symphonic Prog",
      "Symphonic Rock",
      "Synth Funk",
      "Synth Punk",
      "Synthpop",
      "Synthwave",
      "Tape Music",
      "Tech House",
      "Technical Death Metal",
      "Technical Thrash Metal",
      "Techno",
      "Third Stream",
      "Third Wave Ska",
      "Thrash Metal",
      "Thrashcore",
      "Tishoumaren",
      "Totalism",
      "Traditional Doom Metal",
      "Traditional Folk Music",
      "Traditional Pop",
      "Trance",
      "Trancecore",
      "Trap",
      "Trap Metal",
      "Trap [EDM]",
      "Tread",
      "Trip Hop",
      "Tropicanibalismo",
      "Tropicália",
      "Turntable Music",
      "Turntablism",
      "Twee Pop",
      "UK Bass",
      "UK Garage",
      "UK Hard House",
      "UK Hip Hop",
      "Unknown",
      "Vanguarda paulista",
      "Vapor",
      "Vaporwave",
      "Viking Metal",
      "Vocal Jazz",
      "West Coast Hip Hop",
      "Witch House",
      "Wonky",
      "Yacht Rock",
      "Yé-yé",
      "Zeuhl",
      "Zolo",
    ],
  },
  user_score: { type: Number, required: true },
  rating_count: String,
  album_link: String,
  image: { type: String, required: true },
});

const albumModel = model("Album", albumSchema);

module.exports = albumModel;
